language: objective-c
osx_image: xcode7.2

install:
  - ./install_swiftlint.sh

script:
  - swiftlint
  - xctool test -project SwiftLint-TravisCI-Example.xcodeproj -scheme SwiftLint-TravisCI-Example -sdk iphonesimulator

